.\" jf - copy input to output
.\" Copyright (C) 2022 ArcNyxx
.\" see LICENCE file for licensing information
.TH JF 1 jf\-VERSION
.SH NAME
jf \- copy input to output
.SH SYNOPSIS
.SY jf
.RI [ args ...]
.YS
.SH DESCRIPTION
.BR jf (1)
first copies stdin to stdout, then copies all arguments to stdout, separated by
newlines.
.SH AUTHOR
Written by ArcNyxx.
.SH SEE ALSO
.BR cat "(1), " echo (1)
