.\" rev - reverse characterwise
.\" Copyright (C) 2022 ArcNyxx
.\" see LICENCE file for licensing information
.TH REV 1 rev\-VERSION
.SH NAME
rev \- reverse characterwise
.SH SYNOPSIS
.SY rev
.RI [ file ...]
.YS
.SH DESCRIPTION
.BR rev (1)
copies each line in the specified files to standard output, reversing the order
of characters in each line.  If no files are specified, standard input is read.
A single dash stands for standard input when specified as a file.
.SH AUTHOR
Written by ArcNyxx.
.SH SEE ALSO
.BR cat (1)
